CREATE TABLE dependency (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	version varchar(255),
	parent BIGINT
);

CREATE SEQUENCE dependency_sequence START WITH 1 INCREMENT BY 1;

ALTER TABLE dependency ADD CONSTRAINT dependency_unique UNIQUE(name, version);

